### ISSUE TITLE
custom colour theme not working

### ISSUE THREAD

**Issue by k-soomro** [Peltoche/lsd#1141]
- os: Mac OS 15.5
- `lsd --version`: lsd 1.1.5
- `echo $TERM`: xterm-ghostty
- `echo $LS_COLORS`:  

## Expected behavior
custom colour theme should be applied

## Actual behavior

The default colour theme is applied.

![Image](https://github.com/user-attachments/assets/e60fc1d8-fd1e-4dbc-91ba-d1c90f321d63)

My `config.yaml` file contains:

```yaml
color:
  theme: custom
  when: always
indicators: true
sorting:
  dir-grouping: first
```

`colors.yaml` contains:

```yaml
#  Dracula
#  ┬  ┌─┐┌┬┐
#  │  └─┐ ││
#  ┴─┘└─┘─┴┘
# urrick hunt

user: 159                           # cyan
group: 231                          # foreground
permission:
  read: 183                         # blue
  write: 212                        # magenta
  exec: 159                         # cyan
  exec-sticky: 159                  # cyan
  no-access: 210                    # red
date:
  hour-old: 146                     # comment 20% lighter
  day-old: 103                      # comment
  older: 60                         # current line
size:
  none: 60                          # current line
  small: 120                        # green
  medium: 215                       # orange
  large: 210                        # red
inode:
  valid: 231                        # foreground
  invalid: 210                      # red
links:
  valid: 159                        # cyan
  invalid: 210                      # red
tree-edge: 183                      # blue
```

Trying different colour specifications as no effect.
