### ISSUE TITLE
Space Missing Between Icon and Text - v0.20.1 (Pull Req #469)

### ISSUE THREAD

**Issue by tonydm** [Peltoche/lsd#503]
- os: Manjaro
- `lsd --version`: lsd 0.20.1
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`:  Blank, zip, nada

## Expected behavior
A space between icon and text per https://github.com/Peltoche/lsd/pull/469.

Per the Pull Req #469 I understood the enhancement to be in the latest release, 0.20.*

## Actual behavior
No space between icon and text

## Additional detail
1) Removed original w/ `pacman -R lsd`
2) Installed new release w/ `cargo install --git https://github.com/Peltoche/lsd.git --branch master`
3) Ensured lsd was in my path
4) Added `separator: '  '` option to config.yaml
5) Opened new terminal window
6) Removed `separator: '  '` option from config.yaml to so lsd would use default value

I've verified that lsd is reading from the config.yaml file.  I added invalid content to config.yaml file which cased lsd to throw an error.

❯ ll
lsd: Configuration file /home/tonyd/.config/lsd/config.yaml format error, unexpected character: ``' at line 1 column 1.

```
# == Icons ==
icons:
  # When to use icons.
  # When "classic" is set, this is set to "never".
  # Possible values: always, auto, never
  when: auto
  # Which icon theme to use.
  # Possible values: fancy, unicode
  theme: fancy
  separator: ' '
```

Prior to update, some showed a space and some did not.  I don't know what contributed to the difference.  So there's been no change with the update to 0.20.1.

![image](https://user-images.githubusercontent.com/1261605/111337028-f8778000-8632-11eb-94b7-7fa6dca3878b.png)
![image](https://user-images.githubusercontent.com/1261605/111336815-ca923b80-8632-11eb-8c88-18c041397d21.png)
![image](https://user-images.githubusercontent.com/1261605/111336865-d5e56700-8632-11eb-8109-ec7b252e0003.png)

Have I missed something in implementing the updated version?  The installation and config example indicate that the feature is in 0.20.1.

Thank you
