### ISSUE TITLE
Theme config file seems to be ignored

### ISSUE THREAD

**Issue by mwean** [Peltoche/lsd#555]
- os: macOS 11.4
- `lsd --version`:  lsd 0.20.1
- `echo $TERM`:  xterm-256color
- `echo $LS_COLORS`: <empty>

## Expected behavior
Use the colors from the custom config file

## Actual behavior
I have a config file at `~/.config/lsd/config.yaml`:

<details>
<summary>Config Contents</summary>

```yaml
date: relative
size: short
display: almost-all

blocks:
  - permission
  - size
  - date
  - name

icons:
  when: never

sorting:
  dir-grouping: first

color:
  theme: custom
  when: auto
```
</details>

And a theme file at `~/.config/lsd/themes/custom.yaml`:

<details>
<summary>Theme Contents</summary>

```yaml
user: 230
group: 187
permission:
  read: dark_green
  write: dark_yellow
  exec: dark_red
  exec-sticky: 5
  no-access: 245
date:
  hour-old: 40
  day-old: 42
  older: 36
size:
  none: dark_red
  small: dark_red
  medium: dark_red
  large: dark_red
inode:
  valid: 13
  invalid: 245
links:
  valid: 13
  invalid: 245
tree-edge: 245
```
</details>

I just copied the default theme but changed the size entries to `dark_red`. When I run `lsd`, I just get the default theme:

<img width="347" alt="Screenshot 2021-09-26 at 14 58 46" src="https://user-images.githubusercontent.com/732173/134825570-f9ee140b-80b7-4445-8459-d29106c22839.png">

I've tried using different colors, changing the name of the theme, and specifying the absolute path to the theme file with no success.
