### ISSUE TITLE
Theme file doesn't load

### ISSUE THREAD

**Issue by ranebrown** [Peltoche/lsd#575]
- os: macOS 11.6.1
- `lsd --version`: lsd 0.20.1
- `echo $TERM`: tmux-256color
- `echo $LS_COLORS`:
```
fi=37:di=32:ln=36:or=7;36:mi=1;36:pi=93:so=93:bd=93:cd=93:ex=1;31:mh=1;96:su=7;95:sg=1;7;95:tw=1;3;32:ow=1;32:st=3;32:*.c=1;37:*.h=1;37:*.cpp=1;37:*.hpp=1;37:*.cs=1;37:*.asm=1;37:*.py=1;37:*.prl=1;37:*.cgi=1;37:*.pl=1;37:*.json=1;37:*.rs=1;37:*.toml=1;37:*.vim=1;37:*.sh=1;37:*.bat=1;37:*.cmd=1;37:*Makefile=1;35:*tags=2;37:*.pdb=2;37:*.lock=2;37:*.pyc=2;37:*.stackdump=2;37:*.o=2;37:*.d=2;37:*.dll=2;37:*.a=2;37:*.so=2;37:*.gitignore=2;37:*bash_profile=94:*gitconfig=94:*uncrustify=94:*rc=94:*.ini=94:*.conf=94:*.config=94:*.cfg=94:*.jpg=2;34:*.jpeg=2;34:*.JPG=2;34:*.png=2;34:*.PNG=2;34:*.bmp=2;34:*.BMP=2;34:*.gif=2;34:*.svg=2;34:*.ai=2;34:*.ico=2;34:*.tif=2;34:*.tiff=2;34:*.ps=2;34:*.psd=2;34:*.tar=2;37:*.xz=2;37:*.zip=2;37:*.7z=2;37:*.gz=2;37:*.bz2=2;37:*.iso=2;37:*.md=33:*.mkdn=33:*.markdown=33:*README=1;33:*LICENSE=2;33:*.pdf=35:*.doc=35:*.docx=35:*.ppt=35:*.pptx=35:*.xls=35:*.xlsx=35:*.vsd=35:*.vsdx=35:
```

## Expected behavior

Theme file should load and be applied.

Setting a theme in the config file does not seem to load. Other settings work as expected. The theme is in `$XDG_CONFIG_HOME/lsd/themes/oceanic-next.yaml`. It is a copy of the default theme with some colors changed to `red` for testing (also tried other values).

```
color:
  # When to colorize the output.
  # When "classic" is set, this is set to "never".
  # Possible values: never, auto, always
  when: auto

  # When "classic" is set, this is set to "no-color".
  theme: oceanic-next
```

## Actual behavior

Theme not loaded.
