### ISSUE TITLE
Cannot find theme file No such file or directory (os error 2) WSL2

### ISSUE THREAD

**Issue by AH-Merii** [Peltoche/lsd#715]
- os: WSL2
- `lsd --version`: lsd 0.22.0
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: 

## Background
I created a new `config.yaml` file and placed it inside of `~/.config/lsd/config.yaml`. I changed the theme directory inside the `config.yaml` file from `default` to `light_theme` (without the yaml extension). The contents of `~/.config/lsd/themes/light_theme` are the default values found README.md example:  
```
user: 230
group: 187
permission:
  read: dark_green
  write: dark_yellow
  exec: dark_red
  exec-sticky: 5
  no-access: 245
  octal: 6
  acl: dark_cyan
  context: cyan
date:
  hour-old: 40
  day-old: 42
  older: 36
size:
  none: 245
  small: 229
  medium: 216
  large: 172
inode:
  valid: 13
  invalid: 245
links:
  valid: 13
  invalid: 245
tree-edge: 245
```

## Expected behavior
The application should be able to find the `light_theme` file.

## Actual behavior
![image](https://user-images.githubusercontent.com/43741215/183665510-7f525f7d-36c8-4da6-b618-68a6c2fbf54b.png)
```lsd: Not a valid theme: /home/amerii/.config/lsd/themes/light_theme, No such file or directory (os error 2).```

Even though:
![image](https://user-images.githubusercontent.com/43741215/183666175-6fb5254e-805f-4d98-90b8-ee8dc98e1d59.png)
