### ISSUE TITLE
Add support for file category sort

### ISSUE THREAD

**Issue by devnoname120** [Peltoche/lsd#716]
Enhancement of https://github.com/Peltoche/lsd/pull/413

Currently, if you have media files such as `.mkv`, `mp4`, and `webm` they won't appear together but instead be spread out.
Same for `.jpg` and `.png` which is pretty annoying.

An easy improvement would be to sort on `(icon, extension)` as currently many file types belonging in the same category have the same icon.

An alternative would be to rely on the [mime media types](https://www.iana.org/assignments/media-types/media-types.xhtml) but it's far from perfect:
- Some file types are in several categories, with some that don't make sense.
  - e.g. mp4 is `application/mp4`, `audio/mp4`, and `video/mp4`
- The granularity is poor. There are only 10 categories: application, audio, font, example, image, message, model, multipart, text, and video.

A better improvement would be to embed a simple hierarchical category system, where formats are put in the category that makes the most sense. The ordering would be on the key `(category, extension)`.

For example it could look like that:

```yaml
video:
  compression: [h264, h265]
  container: [avi, mp4, mkv]
audio:
  compression: [aac, opus, mp3, wma]
  container: [ogg, wav]
text:
  plain: [txt, log]
  formatted: [md]
  code:
    system: [c, cpp, go]
    web: [html, js, css]
    script: [py, sh] 
```

Etc.
