### ISSUE TITLE
Theme colours for `inode` and `links` are not applied to the output

### ISSUE THREAD

**Issue by UrsaDK** [Peltoche/lsd#763]
- os: macOS 12.6
- `lsd --version`: lsd 0.23.1
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: fi=0:ex=1;32:su=1;4;32:sg=1;4;32:di=1;34:st=1;34:tw=1;4;34:ow=1;4;34:ln=1;36:or=1;4;36:mi=1;31:pi=35:bd=1;35:cd=1;35:so=1;35

<details>
<summary>~/.config/lsd/config.yaml</summary>

```
# This is a shorthand to override some of the options to be backwards compatible
# with `ls`. It affects the "color"->"when", "sorting"->"dir-grouping", "date"
# and "icons"->"when" options.
# Possible values: false, true
classic: false

# == Blocks ==
# This specifies the columns and their order when using the long and the tree
# layout.
# Possible values: permission, user, group, size, size_value, date, name, inode
blocks:
  - permission
  - links
  - user
  - group
  - size
  - date
  - name

# == Color ==
# This has various color options. (Will be expanded in the future.)
color:
  # When to colorize the output.
  # When "classic" is set, this is set to "never".
  # Possible values: never, auto, always
  when: auto
  # How to colorize the output.
  # When "classic" is set, this is set to "no-color".
  # Possible values: default, <theme-file-name>
  # when specifying <theme-file-name>, lsd will look up theme file
  # XDG Base Directory if relative, e.g. ~/.config/lsd/themes/<theme-file-name>.yaml,
  # The file path if absolute
  theme: light

# == Date ==
# This specifies the date format for the date column. The freeform format
# accepts a strftime like string.
# When "classic" is set, this is set to "date".
# Possible values: date, relative, '+<date_format>'
# `date_format` will be a `strftime` formatted value. e.g. `date: '+%d %b %y %X'` will give you a date like this: 17 Jun 21 20:14:55
date: '+%e %b %H:%M'

# == Dereference ==
# Whether to dereference symbolic links.
# Possible values: false, true
dereference: false

# == Display ==
# What items to display. Do not specify this for the default behavior.
# Possible values: all, almost-all, directory-only
# display: all

# == Icons ==
icons:
  # When to use icons.
  # When "classic" is set, this is set to "never".
  # Possible values: always, auto, never
  when: never
  # Which icon theme to use.
  # Possible values: fancy, unicode
  theme: fancy
  # Separator between icon and the name
  # Default to 1 space
  separator: " "

# == Ignore Globs ==
# A list of globs to ignore when listing.
ignore-globs:
  - .DS_Store

# == Indicators ==
# Whether to add indicator characters to certain listed files.
# Possible values: false, true
indicators: true

# == Layout ==
# Which layout to use. "oneline" might be a bit confusing here and should be
# called "one-per-line". It might be changed in the future.
# Possible values: grid, tree, oneline
layout: grid

# == Recursion ==
recursion:
  # Whether to enable recursion.
  # Possible values: false, true
  enabled: false
  # How deep the recursion should go. This has to be a positive integer. Leave
  # it unspecified for (virtually) infinite.
  # depth: 3

# == Size ==
# Specifies the format of the size column.
# Possible values: default, short, bytes
size: short

# == Permission ==
# Specify the format of the permission column
# Possible value: rwx, octal
permission: rwx

# == Sorting ==
sorting:
  # Specify what to sort by.
  # Possible values: extension, name, time, size, version
  column: name
  # Whether to reverse the sorting.
  # Possible values: false, true
  reverse: false
  # Whether to group directories together and where.
  # When "classic" is set, this is set to "none".
  # Possible values: first, last, none
  dir-grouping: none

# == No Symlink ==
# Whether to omit showing symlink targets
# Possible values: false, true
no-symlink: false

# == Total size ==
# Whether to display the total size of directories.
# Possible values: false, true
total-size: false

# == Hyperlink ==
# Attach hyperlink to filenames
# Possible values: always, auto, never
hyperlink: never

# == Symlink arrow ==
# Specifies how the symlink arrow display, chars in both ascii and utf8
symlink-arrow: →

# == Header ==
# Whether to display block headers.
# Possible values: false, true
header: false
```
</details>

<details>
<summary>~/.config/lsd/themes/light.yaml</summary>

```
permission:
  read: dark_grey
  write: dark_grey
  exec: dark_grey
  exec-sticky: red
  octal: dark_grey
  acl: dark_grey
  context: dark_grey
  no-access: dark_grey
user: 240
group: 240
size:
  none: dark_grey
  small: dark_grey
  medium: dark_grey
  large: dark_grey
date:
  hour-old: 240
  day-old: 240
  older: 240
inode:
  valid: green
  invalid: red
links:
  valid: green
  invalid: red
tree-edge: 240
```
</details>

## Expected behavior
I would expect `inode.valid` and `links.valid` to apply to the inode and links columns, as per my theme definitions:

```
inode:
  valid: green
  invalid: red
links:
  valid: green
  invalid: red
```

## Actual behavior
Inode and links columns are displayed in magenta rather than green

<img width="439" alt="Screenshot 2022-11-02 at 15 22 01" src="https://user-images.githubusercontent.com/2833247/199530080-2831ae67-c2e1-4717-8023-aeb1cdf65cba.png">
