### ISSUE TITLE
Instructions for changing icons not clear enough

### ISSUE THREAD

**Issue by lobis** [Peltoche/lsd#771]
Hello,

I am a new user of `lsd` and wanted to change some icons. I followed the instructions of the README but could not get it to work. I assume this is not a bug, just me as a new user not being able to understand the instructions.

- The configuration snippet in the README is badly formatted:

Currently it looks like this. Probably some ` ``` ` are missing.

```
name:
  .trash: 
  .cargo: 
  .emacs.d: 
  a.out: 
extension:
  go: 
  hs: 
  rs: 🦀
filetype:
  dir: 📂
  file: 📄
  pipe: 📩
  socket: 
  executable: 
  symlink-dir: 
  symlink-file: 
  device-char: 
  device-block: ﰩ
  special: 

## External Configurations

### Required

Enable nerd fonts for your terminal, URxvt for example in `.Xresources`:

```sh
URxvt*font:    xft:Hack Nerd Font:style=Regular:size=11
```

Also I think a top level `icons:` and indentation is needed (since I could not get it to work I cannot verify).

So far I have only tested this with the latest version of `lsd` available in `pacman`.

```
docker run -it archlinux
```

```
pacman -S lsd
```

![image](https://user-images.githubusercontent.com/35803280/202223586-8e46a75c-858c-4377-83c4-75a19bfd79b3.png)

![image](https://user-images.githubusercontent.com/35803280/202224315-f9226d4a-9cd5-4dac-ab9f-726b80bd9707.png)

Thanks, I look forward to having cool icons!
