### ISSUE TITLE
Is there a way to specify multiple extentions for one icon in the icon theme file?

### ISSUE THREAD

**Issue by OldWorldOrdr** [Peltoche/lsd#784]
Been using a fork of this project with custom icons but i noticed that you're implementing custom icon themes so I'm switching to that now.  One problem is my theme file is cluttered by a ton of repeats, is there a way i can just list a ton of extensions and put one icon for all of them, it would make my file way less cluttered.  Or even better would be a way to get em all in one go without worrying about missing an extention, like extention groups. There could be a music group, a video group, etc

sample of my theme file:
```
extension:
  mp3: 
  flac: 
  cue: 
  ape: 
  m4a: 
  opus: 
  ogg: 
  wav: 
  wma: 
  sh: 
  bash: 
  zsh: 
  bashrc: 
  zshrc: 
  csh: 
  cshrc: 
  bash_profile: 
  shell: 
  ps1: 
  ksh: 
  fish: 
  elf: 
  bin: 
  awk: 
```

**Comment by OldWorldOrdr** [comment]
also if an icon for a filename is specified in the default theme and not in the user theme, it should fallback to the default theme's version.  I dont wanna specify icons for every single thing in the default theme when im just gonna be using the default icons for most of them anyway

**Comment by OldWorldOrdr** [comment]
bump

**Comment by meain** [comment]
Do you have any format in mind for how we can specify icons for multiple icons in the config file? As for icon groups, while it may simplify the config file, it can get a bit more confusing to new folks as there is now multiple places where they could be specifying icons for somehting.

**Comment by OldWorldOrdr** [comment]
maybe something like
```
extension:
  sh,bash,zsh,bashrc,zshrc,csh,cshrc,bash_profile,shell,ps1,ksh,fish,elf,bin,awk: 
  mp3,flac,cue,ape,m4a,opus,ogg,wav,wma: 
```

**Comment by OldWorldOrdr** [comment]
Also user icon themes should sit on top of the default icon them, not replace it.  If I only want to change one icon and leave the rest as default, I shouldn't need to have an enormous theme file that specifies icons for everything in the default theme

**Comment by meain** [comment]
> maybe something like

The format looks a bit odd for yaml.

> Also user icon themes should sit on top of the default icon them, not replace it.

This should be the behavior, it is a bug in the current implementation.

**Comment by OldWorldOrdr** [comment]
im not too familiar with yaml so idk what a good format would be

**Comment by zwpaper** [comment]
it seems that an icon group would be a better choice

for example:

```yaml
name:
  .trash: 
  .cargo: 
  .emacs.d: 
  a.out: 
extension:
  go: 
  hs: 
  rs: 🦀
filetype:
  dir: 📂
  file: 📄


groups:
- icon: 🦀
  extensions:
  - rs
  - rust
  name:
  - Cargo.toml
  - Cargo.lock
```

then we have 3 level icon configuration

1. default icons
2. group icon theme
3. current icon theme

the later level would overwrite the previous one

**Comment by meain** [comment]
I am not a big fan of this format either. This feels like we are complicating the design of the config file. For most usecases, the user will only be overriding just a few.

**Comment by zwpaper** [comment]
for some use cases, it should at least be quite a few part cases, people would like to modify a lot of icons, like @OldWorldOrdr updating music files, and some issues with changing all icons to UTF-8 icons.

we should provide some more convincing configuration ways to handle those batch operations.

one to one configuration is enough for most users, and they don't have to care about the grouping, but they could if they want if we had.

I don't have a better solution than this group configuration, but I think it is worth doing.

**Comment by OldWorldOrdr** [comment]
hey why do commits suddenly end on november 26?  Plenty of commits before and then nothing

**Comment by r3dArch** [comment]
What if the extension mapping were reversed? Something like:

```yaml
name:
  .trash: 
  .cargo: 
  .emacs.d: 
  a.out: 
icon:
  :
    - go 
  :
    - hs
  🦀:
    - rs
  :
    - mp3
    - flac
    - cue
    - ape
filetype:
  dir: 📂
  file: 📄
```
I changed 'extension' to 'icon' as it seems to make more sense with this change.

I don't know serde super well, but I think it should be possible to create a custom deserializer that can then map this icon field to the `extension` field of the `IconTheme` struct, so there are minimal changes needed and won't affect lookup speed.
